services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  tinder:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    command: ["./tinder", "-redis", "redis:6379", "-users", "10", "-swipes", "100"]
