name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

permissions: {}

jobs:
  unit-tests:
    name: 🧪 Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    concurrency:
      group: unit-${{ github.head_ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: 🧹 Run gofmt check
        run: |
          echo "Checking gofmt formatting..."
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not properly formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: 🧪 Run unit tests
        run: go test -v ./...
